(()=>{
  'use strict';

  const cfg=Object.freeze({...{
    BUILD:'manager-pwa-v0.4.2b-structure-parity-admin',DATA_MODE:'supabase',SUPABASE_URL:'',SUPABASE_PUBLISHABLE_KEY:'',DEFAULT_SEASON:'2026/27',DEFAULT_AREA:'competition'
  },...(window.CC_MANAGER_CONFIG||{})});

  const AREAS={
    mass:{label:'Tömegsport',glyph:'△',modules:[
      ['overview','Áttekintés','△'],['trainings','Edzések','◇'],['calendar','Naptár','□'],['athletes','Sportolók','○'],['passes','Bérletek','▱']
    ]},
    competition:{label:'Versenysport',glyph:'◇',modules:[
      ['overview','Áttekintés','△'],['trainings','Edzések','◇'],['matches','Meccsek','◆'],['calendar','Naptár','□'],['teams','Csapatok','▱'],['players','Játékosok','○'],['fees','Díjak','◎'],['competition','Versenyadatok','≋']
    ]}
  };
  const MOBILE_PRIMARY={mass:['overview','trainings','athletes'],competition:['overview','calendar','players']};
  const ADMIN_MODULES=[
    {group:'Tömegsport',items:[['mass.overview','Áttekintés'],['mass.trainings','Edzések'],['mass.calendar','Naptár'],['mass.athletes','Sportolók'],['mass.passes','Bérletek']]},
    {group:'Versenysport',items:[['competition.overview','Áttekintés'],['competition.trainings','Edzések'],['competition.matches','Meccsek'],['competition.calendar','Naptár'],['competition.teams','Csapatok'],['competition.players','Játékosok'],['competition.fees','Díjak'],['competition.competition','Versenyadatok']]},
    {group:'Rendszer',items:[['settings','Beállítások / adminok']]}
  ];

  const state={
    mode:String(cfg.DATA_MODE||'demo').toLowerCase(),supabase:null,session:null,manager:null,permissions:[],teams:[],players:[],events:[],calendarEvents:[],activityEvents:[],massTrainings:[],massLoadError:'',massDetailCache:new Map(),admins:[],adminTeams:[],adminsLoadError:'',adminEditId:'',adminBusy:false,overview:null,rsvpMatrix:{events:[],players:[],responses:[]},eventRosterCache:new Map(),matrixFilterOpen:false,matrixFilters:{team:'',period:'14',kind:'ALL',status:'ALL',from:'',to:''},
    area:['mass','competition'].includes(cfg.DEFAULT_AREA)?cfg.DEFAULT_AREA:'competition',module:'overview',calendarMode:'week',calendarAnchor:new Date(),calendarTeam:'',calendarType:'',playerTeam:'',playerSearch:'',eventTeam:'',eventPeriod:'upcoming',overviewTeam:'',selectedTeam:'',selectedPlayer:'',pendingEmail:'',loading:false,massActionBusy:''
  };

  const $=sel=>document.querySelector(sel), $$=sel=>Array.from(document.querySelectorAll(sel));
  const esc=v=>String(v??'').replace(/[&<>'"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[ch]));
  const text=v=>String(v??'').trim();
  const dateFmt=new Intl.DateTimeFormat('hu-HU',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:'Europe/Budapest'});
  const dayFmt=new Intl.DateTimeFormat('hu-HU',{weekday:'short',month:'2-digit',day:'2-digit',timeZone:'Europe/Budapest'});
  const timeFmt=new Intl.DateTimeFormat('hu-HU',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Europe/Budapest'});

  const PLAYER_AVATAR_IDS=['alpaca','lion','tiger','panther','lynx','cat','husky','wolf','fox','rabbit','bear','deer','panda','gorilla','monkey','elephant','rhino','hippo','giraffe','buffalo','mammoth','donkey','goat','raccoon','dog','otter','cow','ram','hedgehog','horse','zebra','turtle','penguin','owl','eagle','dolphin','crocodile','frog','shark','moose','extra_zebra','extra_horse','extra_deer','extra_kangaroo','extra_rabbit','extra_eagle','extra_turtle','extra_dolphin','extra_boar','extra_ram','extra_frog','extra_parrot'];
  const AVATAR_INDEX=new Map(PLAYER_AVATAR_IDS.map((id,i)=>[id,i]));
  function avatarHtml(p,size=''){const id=text(p?.avatarId||p?.avatar_id),idx=AVATAR_INDEX.has(id)?AVATAR_INDEX.get(id):-1,cls=`cc-avatar ${size}`.trim();if(idx>=0){const col=idx%8,row=Math.floor(idx/8),x=(col*100/7).toFixed(6),y=(row*100/6).toFixed(6);return `<span class="${cls} animal" role="img" aria-label="Avatar" style="background-position:${x}% ${y}%"></span>`}return `<span class="${cls} monogram" aria-hidden="true">${esc(initials(p?.displayName||p?.name||''))}</span>`}

  function safeDate(v){const d=v instanceof Date?new Date(v):new Date(v);return Number.isNaN(d.getTime())?null:d}
  function fmtDate(v){const d=safeDate(v);return d?dateFmt.format(d):'–'}
  function fmtDay(v){const d=safeDate(v);return d?dayFmt.format(d):'–'}
  function fmtTime(v){const d=safeDate(v);return d?timeFmt.format(d):'–'}
  function initials(v){return text(v).split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]?.toUpperCase()||'').join('')||'M'}
  function routeKey(area=state.area,module=state.module){return module==='settings'?'settings':`${area}.${module}`}
  function currentArea(){return AREAS[state.area]||AREAS.competition}
  function moduleMeta(module=state.module,area=state.area){return (AREAS[area]?.modules||[]).find(x=>x[0]===module)||null}
  function status(message,type=''){const el=$('#globalStatus');if(!el)return;if(!message){el.className='global-status hidden';el.textContent='';return}el.className='global-status'+(type?' '+type:'');el.textContent=message}
  function configured(){return state.mode==='supabase'&&/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(text(cfg.SUPABASE_URL))&&text(cfg.SUPABASE_PUBLISHABLE_KEY)}

  function demoData(){
    const teams=[
      {id:'10000000-0000-4000-8000-000000000001',legacyTeamId:'team_w1',name:'BEAC Női I.',season:'2026/27',color:'#B76508',active:true,playerCount:5,coaches:'Edző A',defaultVenue:'Bogdánfy Sportcsarnok',defaultCourt:'1. pálya'},
      {id:'10000000-0000-4000-8000-000000000002',legacyTeamId:'team_w2',name:'BEAC Női II.',season:'2026/27',color:'#F3D34A',active:true,playerCount:4,coaches:'Edző B',defaultVenue:'Bogdánfy Sportcsarnok',defaultCourt:'2. pálya'},
      {id:'10000000-0000-4000-8000-000000000003',legacyTeamId:'team_m1',name:'BEAC Férfi',season:'2026/27',color:'#6AA84F',active:true,playerCount:4,coaches:'Edző C',defaultVenue:'Bogdánfy Sportcsarnok',defaultCourt:'3. pálya'}
    ];
    const people=['Anna Kiss','Petra Nagy','Luca Tóth','Réka Varga','Nóri Fekete','Dániel Kovács','Márk Szabó','Bence Horváth','Eszter Molnár','Fanni Balogh','Júlia Papp','Ádám Németh','Gergő Lakatos'];
    const positions=['Feladó','Szélső','Center','Átló','Liberó'];
    const players=people.map((name,i)=>({playerId:'p'+(i+1),name,displayName:name,email:`demo${i+1}@example.com`,position:positions[i%positions.length],jerseyNo:(i+1),active:true,licenseNo:'IG'+String(1000+i),medicalValidUntil:i===2?'2026-10-10':'2027-03-31',teamId:teams[i%3].id,teamName:teams[i%3].name,trainingPresent:12+i%5,trainingMarked:15+i%4,matchPresent:3+i%3,matchMarked:4+i%3,jerseySize:'M',shortsSize:'M',avatarId:PLAYER_AVATAR_IDS[i%PLAYER_AVATAR_IDS.length],hasAccount:i%4!==0,membershipStartsOn:'2026-08-15'}));
    const now=Date.now(), day=864e5;
    const events=[];
    for(let i=-8;i<36;i+=2){
      const team=teams[Math.abs(i)%3]; const isMatch=i%8===0; const start=new Date(now+i*day+18*36e5);
      events.push({eventId:'e'+i,teamId:team.id,teamName:team.name,eventType:isMatch?'match':'training',title:isMatch?`${team.name} – Ellenfél`:'Edzés',startsAt:start.toISOString(),endsAt:new Date(start.getTime()+(isMatch?150:120)*60000).toISOString(),court:team.defaultCourt,venue:team.defaultVenue,color:team.color,homeAway:isMatch?'home':null,status:'active',yesCount:8+(Math.abs(i)%5),noCount:1,unknownCount:2+(Math.abs(i)%3)});
    }
    const matrixEvents=events.filter(e=>new Date(e.startsAt)>=new Date()&&new Date(e.startsAt)<new Date(Date.now()+28*day));const matrixPlayers=players.map(p=>({teamId:p.teamId,playerId:p.playerId,name:p.name,displayName:p.displayName,position:p.position,jerseyNo:p.jerseyNo,avatarId:p.avatarId}));const responses=[];matrixEvents.forEach((e,ei)=>matrixPlayers.filter(p=>p.teamId===e.teamId).forEach((p,pi)=>responses.push({eventId:e.eventId,playerId:p.playerId,status:(pi+ei)%5===0?'not_going':((pi+ei)%4===0?'none':'going')})));return {manager:{displayName:'Manager PWA preview',email:'demo@local',role:'preview'},permissions:['*'],teams,players,events,calendarEvents:events,activityEvents:events,rsvpMatrix:{events:matrixEvents,players:matrixPlayers,responses},overview:{teamCount:3,activePlayerCount:players.length,nextEvents:events.filter(x=>new Date(x.startsAt)>=new Date()).slice(0,12),teams}};
  }

  async function ensureSupabaseLibrary(){
    if(window.supabase?.createClient)return;
    await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error('A Supabase klienskönyvtár nem tölthető be.'));document.head.appendChild(s)});
  }
  async function createSupabase(){if(!configured())return null;await ensureSupabaseLibrary();return window.supabase.createClient(text(cfg.SUPABASE_URL),text(cfg.SUPABASE_PUBLISHABLE_KEY),{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
  function normalizeRpc(data){if(typeof data==='string'){try{return JSON.parse(data)}catch(_){return data}}return data}
  async function rpc(name,args={}){if(!state.supabase)throw new Error('Supabase nincs inicializálva.');const {data,error}=await state.supabase.rpc(name,args);if(error)throw error;return normalizeRpc(data)}

  function permissionSet(){return new Set((state.permissions||[]).filter(x=>typeof x==='string'||x?.canView===true).map(x=>typeof x==='string'?x:text(x?.moduleKey)).filter(Boolean))}
  function canAction(key,action='view'){
    const rows=state.permissions||[];
    if(rows.some(x=>x==='*'))return true;
    const direct=rows.find(x=>typeof x==='object'&&text(x?.moduleKey)===key);
    if(direct){if(action==='edit')return direct.canEdit===true;if(action==='notify')return direct.canNotify===true;return direct.canView===true}
    if(action!=='view')return false;
    const p=permissionSet();if(p.has(key))return true;
    const legacy={'competition.overview':'overview','competition.calendar':'calendar','competition.teams':'teams','competition.players':'players','competition.competition':'competition','settings':'settings'};
    return !!legacy[key]&&p.has(legacy[key])
  }
  function can(key){return canAction(key,'view')}

  function showLogin(step){const o=$('#loginOverlay');if(!o)return;o.classList.remove('hidden');['loginLoadingStep','loginEmailStep','loginCodeStep'].forEach(id=>$('#'+id)?.classList.toggle('hidden',id!==step));if(step==='loginEmailStep')setTimeout(()=>$('#loginEmail')?.focus(),20);if(step==='loginCodeStep')setTimeout(()=>$('#loginCode')?.focus(),20)}
  function hideLogin(){$('#loginOverlay')?.classList.add('hidden')}
  function loginMessage(id,msg,error=false){const el=$(id);if(!el)return;el.textContent=msg||'';el.classList.toggle('error',!!error)}
  async function requestCode(){const email=text($('#loginEmail')?.value).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){loginMessage('#loginMsg','Adj meg egy érvényes email címet.',true);return}const b=$('#requestCodeBtn');if(b)b.disabled=true;try{loginMessage('#loginMsg','Kód küldése…');const {error}=await state.supabase.auth.signInWithOtp({email,options:{shouldCreateUser:true}});if(error)throw error;state.pendingEmail=email;$('#loginEmailPreview').textContent=email;showLogin('loginCodeStep');loginMessage('#loginCodeMsg','A kódot elküldtük.')}catch(err){loginMessage('#loginMsg',err.message||'A kód küldése sikertelen.',true)}finally{if(b)b.disabled=false}}
  async function verifyCode(){const token=text($('#loginCode')?.value).replace(/\D/g,'');if(token.length<6){loginMessage('#loginCodeMsg','Írd be az emailben kapott kódot.',true);return}const b=$('#verifyCodeBtn');if(b)b.disabled=true;try{loginMessage('#loginCodeMsg','Ellenőrzés…');const {data,error}=await state.supabase.auth.verifyOtp({email:state.pendingEmail,token,type:'email'});if(error)throw error;state.session=data.session||null;await loadLiveData();hideLogin()}catch(err){loginMessage('#loginCodeMsg',err.message||'A belépés sikertelen.',true)}finally{if(b)b.disabled=false}}

  function applyManager(){const m=state.manager||{};$('#managerName').textContent=m.displayName||m.name||'Manager';$('#managerEmail').textContent=m.email||'–';$('#managerInitials').textContent=initials(m.displayName||m.name||m.email);$('#accountDialogName').textContent=m.displayName||m.name||'Manager';$('#accountDialogEmail').textContent=m.email||'–';$('#runtimeLabel').textContent=configured()?'Supabase direct · scoped':'CONFIG HIBA';$('#dataModePill').textContent=configured()?'SUPABASE':'CONFIG HIBA';$('#dataModeDetail').textContent=configured()?'Supabase Auth + scoped RPC · structure/parity + admin management.':'Hiányos Manager PWA konfiguráció.'}

  async function loadLiveData(){
    state.loading=true;status('Manager adatok frissítése…');
    try{
      const b=await rpc('cc_manager_bootstrap_v1');
      if(!b?.manager)throw new Error('A Manager bootstrap nem adott érvényes fiókot.');
      state.manager=b.manager;state.permissions=Array.isArray(b.permissions)?b.permissions:[];state.teams=Array.isArray(b.teams)?b.teams:[];applyManager();
      const jobs=[];
      if(can('competition.overview'))jobs.push(loadOverview(),loadRsvpMatrix());else{state.overview={};state.rsvpMatrix={events:[],players:[],responses:[]}}
      if(can('competition.teams'))jobs.push(loadTeams());else state.teams=Array.isArray(b.teams)?b.teams:[];
      if(can('competition.players'))jobs.push(loadPlayers());else state.players=[];
      if(can('competition.calendar'))jobs.push(loadCalendar());else state.calendarEvents=[];
      if(can('competition.trainings')||can('competition.matches'))jobs.push(loadActivityEvents());else state.activityEvents=[];state.events=state.calendarEvents;
      if(can('mass.trainings'))jobs.push(loadMassTrainings().catch(err=>{console.error('MGR003 mass trainings load failed',err);state.massTrainings=[];state.massLoadError=text(err?.message||'A Tömegsport írási modul még nincs telepítve.')}));else{state.massTrainings=[];state.massLoadError=''};
      if(canAction('settings','edit'))jobs.push(loadAdmins().catch(err=>{console.error('MGR004 admin load failed',err);state.admins=[];state.adminTeams=[];state.adminsLoadError=text(err?.message||'Az admin-kezelő MGR004 modul még nincs telepítve.')}));else{state.admins=[];state.adminTeams=[];state.adminsLoadError=''};
      await Promise.all(jobs);
      renderChrome();renderView();status('Manager PWA közvetlen Supabase kapcsolat aktív.','success');
    }catch(err){console.error(err);status(err.message||'A Manager adatok betöltése sikertelen.','error');throw err}
    finally{state.loading=false}
  }
  async function loadOverview(teamId=state.overviewTeam||null){const d=await rpc('cc_manager_overview_v1',{p_team_id:teamId});state.overview=d||{}}
  async function loadTeams(){const d=await rpc('cc_manager_teams_v1');state.teams=Array.isArray(d)?d:[];if(state.selectedTeam&&!state.teams.some(t=>t.id===state.selectedTeam))state.selectedTeam=''}
  async function loadPlayers(){const d=await rpc('cc_manager_players_v2',{p_team_id:null,p_query:''});state.players=Array.isArray(d)?d:[]}
  async function loadCalendar(){const {from,to}=calendarWindow();const d=await rpc('cc_manager_calendar_v2',{p_from:from.toISOString(),p_to:to.toISOString(),p_team_id:state.calendarTeam||null});state.calendarEvents=Array.isArray(d)?d:[];state.events=state.calendarEvents}
  async function loadActivityEvents(){const now=new Date(),seasonYear=now.getMonth()>=7?now.getFullYear():now.getFullYear()-1,from=new Date(seasonYear,7,1),to=new Date(seasonYear+1,7,1),jobs=[];if(can('competition.trainings'))jobs.push(rpc('cc_manager_events_v1',{p_from:from.toISOString(),p_to:to.toISOString(),p_kind:'training',p_team_id:null}));if(can('competition.matches'))jobs.push(rpc('cc_manager_events_v1',{p_from:from.toISOString(),p_to:to.toISOString(),p_kind:'match',p_team_id:null}));const parts=await Promise.all(jobs);state.activityEvents=parts.flatMap(x=>Array.isArray(x)?x:[]).sort((a,b)=>eventStart(a)-eventStart(b))}
  async function loadMassTrainings(){const from=new Date(),to=new Date();from.setHours(0,0,0,0);to.setDate(to.getDate()+120);const d=await rpc('cc_manager_mass_trainings_v1',{p_from:localDateKey(from),p_to:localDateKey(to)});state.massTrainings=Array.isArray(d)?d:[];state.massLoadError=''}
  async function loadAdmins(){const d=await rpc('cc_manager_admins_v1');state.admins=Array.isArray(d?.admins)?d.admins:[];state.adminTeams=Array.isArray(d?.teams)?d.teams:state.teams;state.adminsLoadError='';if(state.adminEditId&&state.adminEditId!=='__new__'&&!state.admins.some(a=>text(a.id)===text(state.adminEditId)))state.adminEditId=''}
  async function loadMassEventDetail(eventId,{force=false}={}){const id=text(eventId);if(!force&&state.massDetailCache.has(id))return state.massDetailCache.get(id);const d=await rpc('cc_manager_mass_event_detail_v1',{p_event_id:id});state.massDetailCache.set(id,d||{});return d||{}}
  function matrixRange(){const f=state.matrixFilters||{},now=new Date();now.setHours(0,0,0,0);let from=new Date(now),to=new Date(now);if(f.period==='28')to.setDate(to.getDate()+28);else if(f.period==='CUSTOM'&&f.from&&f.to){from=new Date(f.from+'T00:00:00');to=new Date(f.to+'T00:00:00');to.setDate(to.getDate()+1)}else to.setDate(to.getDate()+14);return{from,to}}
  async function loadRsvpMatrix(){const {from,to}=matrixRange();const d=await rpc('cc_manager_rsvp_matrix_v1',{p_from:from.toISOString(),p_to:to.toISOString(),p_team_id:null});state.rsvpMatrix=d&&typeof d==='object'?d:{events:[],players:[],responses:[]}}
  async function loadEventRoster(eventId){if(state.eventRosterCache.has(eventId))return state.eventRosterCache.get(eventId);const d=await rpc('cc_manager_event_roster_v1',{p_event_id:eventId});const rows=Array.isArray(d)?d:[];state.eventRosterCache.set(eventId,rows);return rows}
  function useDemo(){const d=demoData();Object.assign(state,d);state.calendarEvents=d.calendarEvents;state.activityEvents=d.activityEvents;applyManager();renderChrome();renderView();status('Preview mód: nincs production adatkapcsolat. A csomag nem ír semmit.')}

  function resolveInitialRoute(){const raw=location.hash.replace(/^#/,'');if(raw==='settings'){state.module='settings';return}const [a,m]=raw.split('/');if(AREAS[a]&&AREAS[a].modules.some(x=>x[0]===m)){state.area=a;state.module=m}}
  function setRoute(area,module,{replace=false}={}){if(module==='settings'){state.module='settings';const h='#settings';replace?history.replaceState(null,'',h):history.pushState(null,'',h)}else{state.area=area;state.module=module;const h=`#${area}/${module}`;replace?history.replaceState(null,'',h):history.pushState(null,'',h)}renderChrome();renderView();window.scrollTo({top:0,behavior:'auto'})}
  function switchArea(area){if(!AREAS[area]||state.area===area)return;state.area=area;state.module='overview';setRoute(area,'overview')}

  function renderChrome(){
    const area=currentArea();
    $$('.area-button,.area-choice').forEach(b=>b.classList.toggle('active',b.dataset.area===state.area));
    $('#sideSectionLabel').textContent=area.label.toUpperCase();$('#pageAreaLabel').textContent=state.module==='settings'?'GLOBÁLIS':area.label.toUpperCase();$('#mobileAreaGlyph').textContent=area.glyph;$('#mobileAreaLabel').textContent=area.label;$('#moreAreaLabel').textContent=area.label.toUpperCase();
    const side=$('#sideNav');side.innerHTML=area.modules.filter(m=>can(`${state.area}.${m[0]}`)).map(m=>navButton(m,false)).join('');
    $('#sidebarSettingsSlot').innerHTML=can('settings')?navButton(['settings','Beállítások','⌁'],false,true):'';
    const meta=state.module==='settings'?['settings','Beállítások','⌁']:moduleMeta();$('#pageTitle').textContent=meta?.[1]||'Manager';
    const primary=MOBILE_PRIMARY[state.area]||[];$('#bottomNav').innerHTML=primary.filter(m=>can(`${state.area}.${m}`)).map(m=>navButton(moduleMeta(m),true)).join('')+`<button class="mobile-nav ${primary.includes(state.module)?'':'active-more'}" data-action="more" type="button"><span>☰</span><small>Több</small></button>`;
    const rest=area.modules.filter(m=>!primary.includes(m[0])&&can(`${state.area}.${m[0]}`));$('#mobileMoreGrid').innerHTML=rest.map(m=>`<button class="more-item ${state.module===m[0]?'active':''}" data-route-area="${state.area}" data-route-module="${m[0]}" type="button"><span>${m[2]}</span><div><b>${esc(m[1])}</b><small>${mobileModuleHint(state.area,m[0])}</small></div></button>`).join('')+(can('settings')?`<button class="more-item ${state.module==='settings'?'active':''}" data-route-module="settings" type="button"><span>⌁</span><div><b>Beállítások</b><small>Megjelenés és rendszer</small></div></button>`:'');
    bindDynamicNavigation();
  }
  function navButton(m,mobile=false,settings=false){const active=state.module===m[0];if(mobile)return `<button class="mobile-nav ${active?'active':''}" data-route-area="${state.area}" data-route-module="${m[0]}" type="button"><span>${m[2]}</span><small>${esc(m[1])}</small></button>`;return `<button class="nav-item ${active?'active':''}" ${settings?'data-route-module="settings"':`data-route-area="${state.area}" data-route-module="${m[0]}"`} type="button" aria-label="${esc(m[1])}" title="${esc(m[1])}"><span class="nav-glyph">${m[2]}</span><span class="nav-label">${esc(m[1])}</span></button>`}
  function mobileModuleHint(area,m){const map={trainings:'Edzések kezelése',matches:'Meccsek és részletek',teams:'Csapatok és keretek',fees:'Díjak és fizetések',competition:'Tabella és forrásadatok',passes:'Bérletek és jogosultságok'};return map[m]||`${AREAS[area].label} modul`}
  function bindDynamicNavigation(){$$('[data-route-module]').forEach(b=>b.onclick=()=>{const m=b.dataset.routeModule;if(m==='settings')setRoute(state.area,'settings');else setRoute(b.dataset.routeArea||state.area,m);$('#mobileMoreDialog')?.close()});$('[data-action="more"]')?.addEventListener('click',()=>$('#mobileMoreDialog')?.showModal())}

  function metric(label,value,note){return `<article class="metric-card"><small>${esc(label)}</small><strong>${value==null?'–':esc(value)}</strong><span>${esc(note)}</span></article>`}
  function eventRow(e){const s=e.startsAt||e.starts_at;return `<div class="event-row"><span class="event-accent" style="background:${esc(e.color||'#f7b700')}"></span><div class="event-main"><strong>${esc(e.title||((e.eventType||e.event_type)==='match'?'Meccs':'Edzés'))}</strong><small>${esc(e.teamName||e.team_name||'')} · ${esc(e.court||e.venue||'')}</small></div><div class="event-meta"><b>${esc(fmtDate(s))}</b><span>${esc(fmtTime(s))}</span></div></div>`}
  function teamRow(t){return `<div class="team-row"><span class="team-color" style="background:${esc(t.color||'#f7b700')}"></span><div><strong>${esc(t.name)}</strong><small>${esc(t.season||cfg.DEFAULT_SEASON)}</small></div><span class="team-count">${t.playerCount==null?'–':esc(t.playerCount)} fő</span></div>`}
  function healthRows(items){return items.map(([label,stateText,stateClass])=>`<div class="health-row"><span>${esc(label)}</span><b class="${stateClass||''}">${esc(stateText)}</b></div>`).join('')}

  function num(v){const n=Number(v);return Number.isFinite(n)?n:0}
  function pct(a,b){const aa=num(a),bb=num(b);return bb>0?Math.round(aa*100/bb):null}
  function pctText(a,b){const p=pct(a,b);return p==null?'–':`${p}%`}
  function teamById(id){return state.teams.find(t=>text(t.id)===text(id))||null}
  function playerById(id){return state.players.find(p=>text(p.playerId||p.id)===text(id))||null}
  function eventStart(e){return safeDate(e.startsAt||e.starts_at)}
  function eventEnd(e){return safeDate(e.endsAt||e.ends_at)||eventStart(e)}
  function localDateKey(v){const d=safeDate(v);if(!d)return'';const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Budapest',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(d),m=Object.fromEntries(parts.map(x=>[x.type,x.value]));return `${m.year}-${m.month}-${m.day}`}
  function eventType(e){return text(e.eventType||e.event_type)}
  function eventTeamId(e){return text(e.teamId||e.team_id)}
  function isEventPast(e){const d=eventEnd(e);return d?d.getTime()<Date.now():false}
  function rsvpTotal(e){return num(e.yesCount)+num(e.noCount)+num(e.unknownCount)}
  function attendanceSummary(players=state.players){return players.reduce((acc,p)=>{acc.trainingPresent+=num(p.trainingPresent);acc.trainingMarked+=num(p.trainingMarked);acc.matchPresent+=num(p.matchPresent);acc.matchMarked+=num(p.matchMarked);return acc},{trainingPresent:0,trainingMarked:0,matchPresent:0,matchMarked:0})}
  function teamPlayers(teamId){return state.players.filter(p=>text(p.teamId||p.team_id)===text(teamId))}
  function teamAttendance(teamId){return attendanceSummary(teamPlayers(teamId))}
  function teamOptions(value=''){return '<option value="">Minden csapat</option>'+state.teams.map(t=>`<option value="${esc(t.id)}" ${text(value)===text(t.id)?'selected':''}>${esc(t.name)}</option>`).join('')}
  function rsvpPills(e){return `<div class="rsvp-pills" aria-label="Részvételi jelzések"><span class="yes">J ${num(e.yesCount)}</span><span class="no">N ${num(e.noCount)}</span><span class="unknown">? ${num(e.unknownCount)}</span></div>`}
  function eventPlace(e){return text(e.court)||text(e.venue)||'–'}
  function eventRichRow(e){const s=eventStart(e),kind=eventType(e)==='match'?'MECCS':'EDZÉS';return `<button class="event-rich-row ${isEventPast(e)?'past':''}" type="button" data-event-id="${esc(e.eventId||e.id)}"><span class="event-accent" style="background:${esc(e.color||teamById(eventTeamId(e))?.color||'#f7b700')}"></span><div class="event-date"><b>${esc(s?fmtDate(s):'–')}</b><span>${esc(s?fmtTime(s):'–')}</span></div><div class="event-main"><strong>${esc(e.title||kind)}</strong><small>${esc(e.teamName||e.team_name||'')} · ${esc(eventPlace(e))}</small></div><span class="event-kind">${kind}</span>${rsvpPills(e)}</button>`}
  function detailPair(label,value,cls=''){return `<div class="detail-pair ${cls}"><small>${esc(label)}</small><b>${esc(value==null||value===''?'–':value)}</b></div>`}
  function findEventById(id){const e=[...state.activityEvents,...state.calendarEvents,...(state.rsvpMatrix.events||[])].find(e=>text(e.eventId||e.id)===text(id))||null;if(!e)return null;if(e.yesCount!=null&&e.noCount!=null&&e.unknownCount!=null)return e;const statuses=(state.rsvpMatrix.responses||[]).filter(r=>text(r.eventId)===text(id)).map(r=>text(r.status));return {...e,yesCount:statuses.filter(x=>x==='going').length,noCount:statuses.filter(x=>x==='not_going').length,unknownCount:statuses.filter(x=>x!=='going'&&x!=='not_going').length}}
  function openEventDetail(id){const e=findEventById(id);if(!e)return;const d=$('#entityDialog'),body=$('#entityDialogBody'),title=$('#entityDialogTitle'),s=eventStart(e),en=eventEnd(e);if($('#entityDialogEyebrow'))$('#entityDialogEyebrow').textContent='VERSENYSPORT · ESEMÉNY';title.textContent=e.title||(eventType(e)==='match'?'Meccs':'Edzés');body.innerHTML=`<div class="entity-hero event-entity-hero"><span class="event-detail-mark" style="background:${esc(e.color||'#f7b700')}"></span><div><b>${esc(e.teamName||'–')}</b><span>${esc(eventType(e)==='match'?'Meccs':'Edzés')} · ${esc(s?fmtDate(s):'–')} ${esc(s?fmtTime(s):'–')}</span></div></div><div class="detail-grid">${detailPair('Kezdés',s?`${fmtDate(s)} ${fmtTime(s)}`:'–')}${detailPair('Befejezés',en?fmtTime(en):'–')}${detailPair('Helyszín',e.venue)}${detailPair('Cím',e.address)}${detailPair('Pálya',e.court)}${detailPair('Találkozó',e.meetingAt?`${fmtTime(e.meetingAt)} · ${e.meetingPlace||''}`:(e.meetingPlace||'–'))}</div><div class="panel-subhead"><div><h4>Részvételi jelzések</h4><p>Aktuális RSVP állapot.</p></div></div><div class="attendance-detail rsvp-detail"><div><small>Jövök</small><b>${num(e.yesCount)}</b><span>fő</span></div><div><small>Nem jövök</small><b>${num(e.noCount)}</b><span>fő</span></div><div><small>Nincs válasz</small><b>${num(e.unknownCount)}</b><span>fő</span></div></div>`;d?.showModal()}
  function bindEventDetailActions(){$$('[data-event-id]').forEach(el=>el.addEventListener('click',()=>openEventDetail(el.dataset.eventId)))}
  function matrixResponseMap(){const m=new Map();(state.rsvpMatrix.responses||[]).forEach(r=>m.set(`${text(r.eventId)}:${text(r.playerId)}`,text(r.status)||'none'));return m}
  function matrixFilteredEvents(){const f=state.matrixFilters||{};return (state.rsvpMatrix.events||[]).filter(e=>(!f.team||eventTeamId(e)===f.team)&&(f.kind==='ALL'||(f.kind==='TRAINING'&&eventType(e)==='training')||(f.kind==='MATCH'&&eventType(e)==='match'))).sort((a,b)=>eventStart(a)-eventStart(b))}
  function gridGivenName(p){const raw=text(p?.displayName||p?.name||'');if(!raw)return'–';const parts=raw.split(/\s+/).filter(Boolean);return parts[0]||raw}
  function matrixTeamHtml(teamId,events,map){
    let players=(state.rsvpMatrix.players||[]).filter(p=>text(p.teamId)===text(teamId));
    const f=state.matrixFilters||{};
    if(f.status!=='ALL')players=players.filter(p=>events.some(e=>map.get(`${text(e.eventId)}:${text(p.playerId)}`)===f.status));
    players.sort((a,b)=>(num(a.jerseyNo)||9999)-(num(b.jerseyNo)||9999)||text(a.displayName||a.name).localeCompare(text(b.displayName||b.name),'hu'));
    const t=teamById(teamId);if(!events.length)return'';
    const head=`<th class="matrix-event-col matrix-event-side sticky-matrix-col">Alkalom</th><th class="matrix-count-col matrix-count-head">Fő</th>${players.map(p=>`<th class="matrix-player-head" title="${esc(p.displayName||p.name)}"><span class="grid-player-head-inner">${avatarHtml(p,'matrix')}<span class="grid-player-label">${esc(gridGivenName(p))}</span></span></th>`).join('')}`;
    const body=events.map(e=>{const going=players.filter(p=>map.get(`${text(e.eventId)}:${text(p.playerId)}`)==='going').length;const kind=eventType(e)==='match'?'Meccs':'Edzés';return `<tr><th class="matrix-event-col matrix-event-side sticky-matrix-col"><button class="matrix-event-side-btn" type="button" data-event-id="${esc(e.eventId)}"><span class="matrix-event-copy"><b>${esc(e.title||kind)}</b><small>${esc(fmtDate(eventStart(e)))} · ${esc(fmtTime(eventStart(e)))}</small></span></button></th><td class="matrix-count-col matrix-count-cell"><strong>${going}</strong></td>${players.map(p=>{const st=map.get(`${text(e.eventId)}:${text(p.playerId)}`);if(st==='going')return'<td class="matrix-cell going" title="Jövök"><span class="matrix-status">✓</span></td>';if(st==='not_going')return'<td class="matrix-cell not-going" title="Nem jövök"><span class="matrix-status">✕</span></td>';return'<td class="matrix-cell none" title="Nincs válasz"><span class="matrix-status">·</span></td>'}).join('')}</tr>`}).join('');
    return `<section class="matrix-team-section"><div class="matrix-team-title"><strong>${esc(t?.name||'Csapat')}</strong><span>${events.length} esemény · ${players.length} játékos</span></div><div class="matrix-scroll matrix-mobile-v2 matrix-freeze-v3"><table class="rsvp-matrix season-matrix transposed-matrix"><thead><tr>${head}</tr></thead><tbody>${body}</tbody></table></div></section>`
  }
  function matrixFiltersHtml(){const f=state.matrixFilters||{},active=!!f.team||f.period!=='14'||f.kind!=='ALL'||f.status!=='ALL'||!!f.from||!!f.to,custom=f.period==='CUSTOM';return `<div class="matrix-filter-wrap"><div class="matrix-filter-head"><button class="matrix-filter-toggle ${state.matrixFilterOpen?'open':''} ${active?'has-filter':''}" id="matrixFilterToggle" type="button"><span class="triangle-icon"></span>Szűrők</button>${state.matrixFilterOpen&&active?'<button class="filter-reset" id="matrixFilterReset" type="button">Szűrők törlése</button>':''}</div><div class="matrix-filter-panel ${state.matrixFilterOpen?'open':''}"><label>Csapat<select data-matrix-filter="team">${teamOptions(f.team)}</select></label><label>Időszak<select data-matrix-filter="period"><option value="14" ${f.period==='14'?'selected':''}>Következő 2 hét</option><option value="28" ${f.period==='28'?'selected':''}>Következő 4 hét</option><option value="CUSTOM" ${f.period==='CUSTOM'?'selected':''}>Egyéni időszak</option></select></label><label>Eseménytípus<select data-matrix-filter="kind"><option value="ALL" ${f.kind==='ALL'?'selected':''}>Edzés + meccs</option><option value="TRAINING" ${f.kind==='TRAINING'?'selected':''}>Csak edzés</option><option value="MATCH" ${f.kind==='MATCH'?'selected':''}>Csak meccs</option></select></label><label>Jelzés<select data-matrix-filter="status"><option value="ALL" ${f.status==='ALL'?'selected':''}>Minden játékos</option><option value="going" ${f.status==='going'?'selected':''}>Jövök</option><option value="not_going" ${f.status==='not_going'?'selected':''}>Nem jövök</option><option value="none" ${f.status==='none'?'selected':''}>Nincs válasz</option></select></label>${custom?`<label>Időszak eleje<input type="date" data-matrix-filter="from" value="${esc(f.from||'')}"></label><label>Időszak vége<input type="date" data-matrix-filter="to" value="${esc(f.to||'')}"></label>`:''}</div></div>`}
  function renderMatrix(){const events=matrixFilteredEvents(),map=matrixResponseMap(),teamIds=state.matrixFilters.team?[state.matrixFilters.team]:state.teams.map(t=>t.id);return `<div class="parity-matrix"><div class="parity-matrix-head"><div><h3>Részvételi jelzések</h3><p>Jövök / Nem jövök / Nincs válasz · Player Grid v3 freeze-pane nézet.</p></div></div>${matrixFiltersHtml()}${teamIds.map(id=>matrixTeamHtml(id,events.filter(e=>eventTeamId(e)===text(id)),map)).join('')||emptyInline('Nincs esemény a kiválasztott szűréssel.')}</div>`}
  function bindMatrix(){const tog=$('#matrixFilterToggle');if(tog)tog.onclick=()=>{state.matrixFilterOpen=!state.matrixFilterOpen;renderOverview()};$('#matrixFilterReset')?.addEventListener('click',async()=>{state.matrixFilters={team:'',period:'14',kind:'ALL',status:'ALL',from:'',to:''};if(configured())await loadRsvpMatrix();renderOverview()});$$('[data-matrix-filter]').forEach(el=>el.addEventListener('change',async()=>{const k=el.dataset.matrixFilter,old=state.matrixFilters[k];state.matrixFilters[k]=el.value;if(k==='period'||k==='from'||k==='to'){try{if(configured())await loadRsvpMatrix()}catch(err){state.matrixFilters[k]=old;status(err.message,'error')}}renderOverview()}));bindEventDetailActions()}
  function renderOverview(){
    if(state.area!=='competition'){
      const rows=(state.massTrainings||[]).filter(e=>safeDate(e.startsAt)?.getTime()>=Date.now()-3600000).sort((a,b)=>safeDate(a.startsAt)-safeDate(b.startsAt));
      const totalBookings=rows.reduce((n,e)=>n+num(e.totalActive),0),totalWait=rows.reduce((n,e)=>n+num(e.waitlistCount),0),closed=rows.filter(e=>text(e.registrationMode)==='WAITLIST_ONLY').length;
      $('#viewContent').innerHTML=`<div class="page-intro"><div><h2>Tömegsport áttekintés</h2><p>A régi Manager logikája: közelgő alkalmak, jelentkezések és várólista egy helyen.</p></div><span class="read-only-badge write-enabled">SUPABASE LIVE</span></div><div class="overview-summary parity-summary"><div><strong>${rows.length}</strong><span>Közelgő edzés</span></div><div><strong>${totalBookings}</strong><span>Aktív jelentkezés</span></div><div><strong>${totalWait}</strong><span>Várólistán</span></div><div><strong>${closed}</strong><span>Csak várólista</span></div></div><div class="mass-overview-grid"><article class="panel"><div class="panel-head"><div><h3>Következő edzések</h3><p>Kattints az edzésre a jelentkezők és a várólista megnyitásához.</p></div><button class="button quiet small" id="massOverviewAll" type="button">Összes edzés</button></div><div class="mass-overview-list">${rows.slice(0,10).map(e=>massOverviewRow(e)).join('')||emptyInline('Nincs közelgő Tömegsport edzés.')}</div></article><article class="panel"><div class="panel-head"><div><h3>Jelentkezési állapot</h3><p>Azonnali áttekintés a kapukról.</p></div></div><div class="health-list">${healthRows([['Publikus alkalmak',String(rows.filter(e=>e.publicRegistrationActive!==false).length),'ok'],['Csak várólista',String(closed),closed?'warn':'ok'],['Várakozók',String(totalWait),totalWait?'warn':''],['MGR003',state.massLoadError?'HIÁNYZIK':'AKTÍV',state.massLoadError?'error':'ok']])}</div></article></div>`;
      $('#massOverviewAll')?.addEventListener('click',()=>setRoute('mass','trainings'));
      $$('[data-mass-detail]').forEach(b=>b.addEventListener('click',()=>openMassEventDetail(b.dataset.massDetail)));
      return;
    }
    const now=Date.now(),trainingUntil=now+14*864e5,matchUntil=now+31*864e5,overviewFallback=Array.isArray(state.overview?.nextEvents)?state.overview.nextEvents:[],events=(state.activityEvents.length?state.activityEvents:overviewFallback).filter(e=>!isEventPast(e)),trainings=events.filter(e=>eventType(e)==='training'&&(eventStart(e)?.getTime()||0)<trainingUntil),matches=events.filter(e=>eventType(e)==='match'&&(eventStart(e)?.getTime()||0)<matchUntil),teamsWithProgram=new Set(events.map(eventTeamId).filter(Boolean));
    $('#viewContent').innerHTML=`<div class="page-intro"><div><h2>Versenysport áttekintés</h2><p>Következő edzések, meccsek és csapatprogram egy helyen.</p></div><span class="read-only-badge">PLAYER GRID PARITY</span></div><div class="overview-summary parity-summary"><div><strong>${trainings.length}</strong><span>Közelgő edzés</span></div><div><strong>${matches.length}</strong><span>Közelgő meccs</span></div><div><strong>${teamsWithProgram.size}</strong><span>Csapat programmal</span></div></div><div class="parity-overview-grid"><article class="panel parity-matrix-card">${renderMatrix()}</article><article class="panel"><div class="panel-head"><div><h3>Következő meccsek</h3><p>következő 1 hónap</p></div><button class="button quiet small" id="allMatchesBtn" type="button">Összes</button></div><div class="legacy-overview-list">${matches.slice(0,8).map(e=>`<button type="button" class="legacy-overview-row" data-event-id="${esc(e.eventId||e.id)}" style="--team-color:${esc(e.color||teamById(eventTeamId(e))?.color||'#f7b700')}"><span class="legacy-overview-accent"></span><div><b>${esc(e.teamName||'')}</b><small>${esc(e.title||'Meccs')}</small></div><div><b>${esc(fmtDate(eventStart(e)))}</b><small>${esc(fmtTime(eventStart(e)))}</small></div><div><b>${esc(eventPlace(e))}</b><small>Pálya / helyszín</small></div><div>${rsvpPills(e)}</div></button>`).join('')||emptyInline('Nincs közelgő meccs.')}</div></article></div>`;
    $('#allMatchesBtn')?.addEventListener('click',()=>setRoute('competition','matches'));bindMatrix();bindEventDetailActions();
  }

  function renderModule(){
    const m=state.module;
    if(m==='settings'){if(!can('settings')){renderPermissionDenied();return}renderSettings();return}
    if(!can(`${state.area}.${m}`)){renderPermissionDenied();return}
    if(m==='overview'){renderOverview();return}
    if(m==='calendar'){renderCalendar();return}
    if(state.area==='competition'&&m==='teams'){renderTeams();return}
    if(state.area==='competition'&&m==='players'){renderPlayers();return}
    if(state.area==='competition'&&m==='trainings'){renderEventList('Edzések','A versenycsapatok edzései.',e=>(e.eventType||e.event_type)==='training');return}
    if(state.area==='competition'&&m==='matches'){renderEventList('Meccsek','Hazai és idegenbeli mérkőzések.',e=>(e.eventType||e.event_type)==='match');return}
    if(state.area==='competition'&&m==='fees'){renderPlaceholder('Díjak','A jelenlegi havi díj-/fizetési mátrix production parityje ide kerül.',['Játékosonkénti havi státusz','Edzői díj','Bérlet','Audit / felülírás']);return}
    if(state.area==='competition'&&m==='competition'){renderPlaceholder('Versenyadatok','Competition Core: tabella, teljes meccslista, BRSZ/MRSZ források és konfliktusok.',['054 Competition Core backend előtt nincs production adat','Saját csapatok meccsei az events bridge-en keresztül','Külső liga-meccsek nem kerülnek az events táblába']);return}
    if(state.area==='mass'&&m==='trainings'){renderMassTrainings();return}
    if(state.area==='mass'&&m==='athletes'){renderPlaceholder('Sportolók','A Tömegsport sportolói adatbázis és jelentkezési előzmények migrációs helye.',['keresés és státusz','bérletellenőrzés','edzéselőzmény']);return}
    if(state.area==='mass'&&m==='passes'){renderPlaceholder('Bérletek','Bérletek és jogosultságok migrációs helye.',['5 / 10 alkalmas bérlet','érvényességi kivételek','ellenőrzési állapot']);return}
    renderPlaceholder(moduleMeta()?.[1]||'Modul','A modul foundation helye.',['read-only migráció','parity teszt','write csak később']);
  }

  function massOverviewRow(e){const s=safeDate(e.startsAt),st=massTrainingStatus(e);return `<button class="mass-overview-row" type="button" data-mass-detail="${esc(e.eventId)}"><span class="mass-training-dot" style="background:${esc(e.color||'#f7b700')}"></span><div><b>${esc(e.level||'Edzés')}</b><small>${esc(s?fmtDate(s):'–')} · ${esc(s?fmtTime(s):'–')} · ${esc(e.court||'Pálya –')}</small></div><div class="mass-overview-numbers"><b>${num(e.totalActive)} fő</b><small>${num(e.waitlistCount)} váró</small></div><span class="status-pill ${st.cls}">${st.label}</span></button>`}
  function massTrainingStatus(e){
    if(e.publicRegistrationActive===false)return {label:'PUBLIKUS KI',cls:'muted'};
    if(text(e.registrationMode)==='WAITLIST_ONLY')return {label:'CSAK VÁRÓLISTA',cls:'warn'};
    return {label:'NYITVA',cls:'ok'}
  }
  function massTrainingRow(e,canEdit){
    const s=safeDate(e.startsAt),en=safeDate(e.endsAt),closed=text(e.registrationMode)==='WAITLIST_ONLY',sport7=text(e.sessionType).toUpperCase()==='SPORT7',st=massTrainingStatus(e),busy=state.massActionBusy===text(e.eventId);
    const action=!e.publicRegistrationActive?'<span class="mass-gate-note">A publikus jelentkezés ki van kapcsolva.</span>':sport7?'<span class="mass-gate-note">SPORT7 külön jelentkezési csatorna.</span>':`<button class="button ${closed?'quiet':'danger'} small mass-gate-button" type="button" data-mass-gate="${esc(e.eventId)}" data-close="${closed?'0':'1'}" ${(!canEdit||busy)?'disabled':''}>${busy?'Mentés…':(closed?'Jelentkezés megnyitása':'Jelentkezés lezárása')}</button>`;
    return `<div class="mass-training-row ${closed?'waitlist-only':''}"><button class="mass-training-main mass-training-open" type="button" data-mass-detail="${esc(e.eventId)}"><span class="mass-training-dot" style="background:${esc(e.color||'#f7b700')}"></span><div><b>${esc(e.level||'Edzés')}</b><small>${esc(s?fmtDate(s):'–')} · ${esc(s?fmtTime(s):'–')}${en?'–'+esc(fmtTime(en)):''} · ${esc(e.court||'Pálya –')}</small></div></button><div class="mass-training-stat"><b>${num(e.totalActive)}</b><small>jelentkező</small></div><div class="mass-training-stat"><b>${num(e.waitlistCount)}</b><small>várólista</small></div><div class="mass-training-stat"><b>${closed?'–':num(e.free)}</b><small>szabad hely</small></div><div><span class="status-pill ${st.cls}">${st.label}</span></div><div class="mass-training-action">${action}</div></div>`
  }
  function renderMassTrainings(){
    const rows=(state.massTrainings||[]).filter(e=>safeDate(e.startsAt)?.getTime()>=Date.now()-3600000),canEdit=canAction('mass.trainings','edit'),loadError=text(state.massLoadError);
    $('#viewContent').innerHTML=`<div class="page-intro"><div><h2>Edzések</h2><p>Tömegsport jelentkezések és várólista vezérlése közvetlenül Supabase-ből.</p></div><span class="read-only-badge ${loadError?'':'write-enabled'}">${loadError?'MGR003 · NINCS TELEPÍTVE':'MGR003 · WRITE'}</span></div><article class="panel mass-training-panel"><div class="panel-head"><div><h3>Közelgő edzések</h3><p>Lezáráskor a meglévő jelentkezők maradnak, új sportoló csak várólistára kerülhet.</p></div><button class="button quiet small" id="massTrainingsRefresh" type="button">Frissítés</button></div>${loadError?`<div class="migration-note error"><b>A Tömegsport írási modul még nincs telepítve.</b><span>Futtasd a csomag SQL/MGR003_MASS_REGISTRATION_GATE_SAFE.sql fájlját a Supabase-ben, majd frissítsd ezt a nézetet.</span><small>${esc(loadError)}</small></div>`:`<div class="mass-training-header"><div>Edzés</div><div>Jel.</div><div>Váró</div><div>Szabad</div><div>Állapot</div><div>Művelet</div></div><div class="mass-training-list">${rows.map(e=>massTrainingRow(e,canEdit)).join('')||emptyInline('Nincs közelgő Tömegsport edzés.')}</div>${canEdit?'':'<div class="migration-note"><b>Megtekintési mód:</b> ehhez a fiókhoz nincs mass.trainings szerkesztési jogosultság.</div>'}`}</article>`;
    $('#massTrainingsRefresh')?.addEventListener('click',async()=>{try{status('Tömegsport edzések frissítése…');await loadMassTrainings();renderMassTrainings();status('Frissítve.','success')}catch(err){state.massLoadError=text(err?.message||'A Tömegsport írási modul még nincs telepítve.');renderMassTrainings();status(state.massLoadError,'error')}});
    $$('[data-mass-gate]').forEach(b=>b.addEventListener('click',()=>toggleMassRegistrationGate(b.dataset.massGate,b.dataset.close==='1')));
    $$('[data-mass-detail]').forEach(b=>b.addEventListener('click',()=>openMassEventDetail(b.dataset.massDetail)))
  }
  function massPersonRow(r,kind='booking'){const attendance=text(r.attendance),sub=safeDate(r.submittedAt);return `<div class="mass-person-row"><div><b>${esc(r.name||'Névtelen')}</b><small>${esc(r.email||'–')}</small></div><div><b>${esc(r.passNumber||'–')}</b><small>${esc(r.passStatus||'')}</small></div><div><b>${esc(kind==='booking'?(attendance||'NINCS RÖGZÍTVE'):(r.status||'VÁRAKOZIK'))}</b><small>${sub?esc(fmtDate(sub)+' '+fmtTime(sub)):''}</small></div></div>`}
  async function openMassEventDetail(eventId){const d=$('#entityDialog'),body=$('#entityDialogBody'),title=$('#entityDialogTitle');if(!d||!body||!title)return;if($('#entityDialogEyebrow'))$('#entityDialogEyebrow').textContent='TÖMEGSPORT · EDZÉS';title.textContent='Tömegsport edzés';body.innerHTML='<div class="loading-inline">Edzés betöltése…</div>';d.showModal();try{const data=await loadMassEventDetail(eventId,{force:true}),e=data?.event||{};const bookings=Array.isArray(data?.bookings)?data.bookings:[],wait=Array.isArray(data?.waitlist)?data.waitlist:[];title.textContent=e.level||'Edzés';body.innerHTML=`<div class="entity-hero event-entity-hero"><span class="event-detail-mark" style="background:${esc(e.color||'#f7b700')}"></span><div><b>${esc(e.level||'Edzés')}</b><span>${esc(fmtDate(e.startsAt))} · ${esc(fmtTime(e.startsAt))} · ${esc(e.court||'Pálya –')}</span></div></div><div class="attendance-detail"><div><small>Jelentkező</small><b>${bookings.length}</b><span>fő</span></div><div><small>Várólista</small><b>${wait.length}</b><span>fő</span></div><div><small>Kapacitás</small><b>${num(e.capacity)}</b><span>fő</span></div></div><div class="panel-subhead"><div><h4>Jelentkezők</h4><p>Aktív foglalások és rögzített jelenlét.</p></div></div><div class="mass-person-list">${bookings.map(r=>massPersonRow(r,'booking')).join('')||emptyInline('Nincs aktív jelentkező.')}</div><div class="panel-subhead"><div><h4>Várólista</h4><p>Várakozó és felajánlott helyek.</p></div></div><div class="mass-person-list">${wait.map(r=>massPersonRow(r,'wait')).join('')||emptyInline('A várólista üres.')}</div>`}catch(err){console.error(err);body.innerHTML=`<div class="migration-note error"><b>A részletes Tömegsport nézethez MGR004 szükséges.</b><span>${esc(err.message||'Betöltési hiba')}</span></div>`}}
  async function toggleMassRegistrationGate(eventId,closeToWaitlist){
    if(!canAction('mass.trainings','edit')||state.massActionBusy)return;
    const e=(state.massTrainings||[]).find(x=>text(x.eventId)===text(eventId));if(!e)return;
    const label=`${e.level||'Edzés'} · ${fmtDate(e.startsAt)} ${fmtTime(e.startsAt)}`;
    const question=closeToWaitlist?`${label}\n\nLezárod a közvetlen jelentkezést?\n\nA meglévő jelentkezések megmaradnak. Új sportoló csak várólistára kerülhet, és a várólista automatikus előreléptetése szünetel.`:`${label}\n\nÚjra megnyitod a közvetlen jelentkezést?\n\nA meglévő kapacitás ismét közvetlen jelentkezésre használható, és az új jelentkezők közvetlenül bekerülhetnek.`;
    if(!window.confirm(question))return;
    state.massActionBusy=text(eventId);renderMassTrainings();
    try{status(closeToWaitlist?'Jelentkezés lezárása…':'Jelentkezés megnyitása…');await rpc('cc_manager_mass_registration_gate_v1',{p_event_id:eventId,p_waitlist_only:closeToWaitlist});await loadMassTrainings();status(closeToWaitlist?'Jelentkezés lezárva: csak várólista.':'Jelentkezés újra megnyitva.','success')}
    catch(err){console.error(err);status(err.message||'A jelentkezési állapot módosítása sikertelen.','error')}
    finally{state.massActionBusy='';renderMassTrainings()}
  }

  function renderPlaceholder(title,copy,items=[]){$('#viewContent').innerHTML=`<div class="page-intro"><div><h2>${esc(title)}</h2><p>${esc(copy)}</p></div><span class="migration-badge">MIGRÁCIÓ</span></div><article class="panel placeholder-panel"><div class="placeholder-glyph">${moduleMeta()?.[2]||'◇'}</div><div><h3>${esc(title)}</h3><p>${esc(copy)}</p><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="migration-note"><b>V0.4 szabály:</b> ez a modul még nem váltja le a régi Manager production funkcióját.</div></div></article>`}
  function renderPermissionDenied(){$('#viewContent').innerHTML=`<article class="panel placeholder-panel"><div class="placeholder-glyph">⊘</div><div><h3>Nincs hozzáférés</h3><p>Ehhez a Manager modulhoz a jelenlegi fiókodnak nincs megtekintési jogosultsága.</p></div></article>`}
  function migrationNotice(textValue){return `<div class="migration-notice"><b>Read-only foundation</b><span>${esc(textValue)}</span></div>`}
  function emptyInline(v){return `<div class="empty-inline">${esc(v)}</div>`}

  function filteredActivityEvents(predicate){
    const now=Date.now();return state.activityEvents.filter(e=>predicate(e)&&(!state.eventTeam||eventTeamId(e)===state.eventTeam)&&(state.eventPeriod==='all'||(state.eventPeriod==='upcoming'&&!isEventPast(e))||(state.eventPeriod==='past'&&isEventPast(e)))).sort((a,b)=>eventStart(a)-eventStart(b));
  }
  function eventStatusLabel(e){return isEventPast(e)?'LEZÁRT':(text(e.status||'active').toLowerCase()==='active'?'AKTÍV':text(e.status||'').toUpperCase()||'AKTÍV')}
  function rosterGroup(title,rows,kind){return `<section class="roster-group ${kind}"><h4>${esc(title)} <span>${rows.length}</span></h4><div>${rows.map(p=>`<div class="roster-name-row">${avatarHtml(p,'tiny')}<span><b>${esc(p.displayName||p.name)}</b><small>${esc(p.position||'–')}${p.jerseyNo!=null?` · #${esc(p.jerseyNo)}`:''}</small></span></div>`).join('')||'<small class="roster-empty">Nincs játékos.</small>'}</div></section>`}
  async function toggleEventRoster(eventId,button){const holder=document.querySelector(`[data-roster-holder="${CSS.escape(eventId)}"]`);if(!holder)return;const opening=holder.hidden;holder.hidden=!opening;button?.setAttribute('aria-expanded',String(opening));button?.classList.toggle('open',opening);if(!opening)return;if(holder.dataset.loaded==='1')return;holder.innerHTML='<div class="roster-loading">Névsor betöltése…</div>';try{const rows=configured()?await loadEventRoster(eventId):[];holder.dataset.loaded='1';holder.innerHTML=`<div class="roster-groups">${rosterGroup('Jövök',rows.filter(x=>x.status==='going'),'going')}${rosterGroup('Nem jövök',rows.filter(x=>x.status==='not_going'),'not-going')}${rosterGroup('Nincs válasz',rows.filter(x=>x.status!=='going'&&x.status!=='not_going'),'none')}</div>`}catch(err){holder.innerHTML=`<div class="roster-loading error">${esc(err.message||'A névsor betöltése nem sikerült.')}</div>`}}
  function renderEventList(title,copy,predicate){
    const rows=filteredActivityEvents(predicate),active=!!state.eventTeam||state.eventPeriod!=='upcoming';
    $('#viewContent').innerHTML=`<div class="page-intro"><div><h2>${esc(title)}</h2><p>${esc(copy)} A korábbi Manager információsűrűségével.</p></div><span class="read-only-badge">READ-ONLY PARITY</span></div><div class="event-filter-head"><button class="matrix-filter-toggle ${active?'has-filter':''}" id="eventFiltersToggle" aria-expanded="false" type="button"><span class="triangle-icon"></span>Szűrők</button></div><div class="filter-panel parity-event-filters" id="eventFiltersPanel" hidden><label class="field compact"><span>Csapat</span><select id="eventTeamFilter">${teamOptions(state.eventTeam)}</select></label><label class="field compact"><span>Időszak</span><select id="eventPeriodFilter"><option value="upcoming" ${state.eventPeriod==='upcoming'?'selected':''}>Aktuális / közelgő</option><option value="past" ${state.eventPeriod==='past'?'selected':''}>Elmúlt</option><option value="all" ${state.eventPeriod==='all'?'selected':''}>Mind</option></select></label><button class="filter-reset" id="eventFilterReset" ${active?'':'hidden'} type="button">Szűrők törlése</button></div><article class="panel event-table-panel"><div class="legacy-event-table"><div class="legacy-event-header"><div>Esemény / csapat</div><div>Időpont</div><div>Pálya / helyszín</div><div>Jövök</div><div>Nem jövök</div><div>Nincs válasz</div><div>Státusz</div><div></div></div>${rows.map(e=>`<div class="legacy-event-item ${isEventPast(e)?'past':''}"><div class="legacy-event-row"><button class="event-title-button" type="button" data-event-id="${esc(e.eventId||e.id)}"><span class="legacy-event-accent" style="background:${esc(e.color||teamById(eventTeamId(e))?.color||'#f7b700')}"></span><span><b>${esc(e.teamName||'')}</b><small>${esc(e.title||((eventType(e)==='match')?'Meccs':'Edzés'))} · ${eventType(e)==='match'?'Meccs':'Edzés'}</small></span></button><div><b>${esc(fmtDate(eventStart(e)))}</b><small>${esc(fmtTime(eventStart(e)))}${eventEnd(e)?` – ${esc(fmtTime(eventEnd(e)))}`:''}</small></div><div><b>${esc(e.court||'–')}</b><small>${esc(e.venue||'')}</small></div><div class="rsvp-number going">${num(e.yesCount)}</div><div class="rsvp-number not-going">${num(e.noCount)}</div><div class="rsvp-number none">${num(e.unknownCount)}</div><div><span class="status-pill ${isEventPast(e)?'':'ok'}">${esc(eventStatusLabel(e))}</span></div><button class="roster-chevron" type="button" data-roster-toggle="${esc(e.eventId||e.id)}" aria-expanded="false" aria-label="Névsor megnyitása"><span>⌄</span></button></div><div class="legacy-event-roster" data-roster-holder="${esc(e.eventId||e.id)}" hidden></div></div>`).join('')||emptyInline('Nincs esemény ebben a szűrésben.')}</div></article>`;
    const toggle=$('#eventFiltersToggle'),panel=$('#eventFiltersPanel');toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));toggle.classList.toggle('open',open);panel.hidden=!open});$('#eventTeamFilter')?.addEventListener('change',e=>{state.eventTeam=e.target.value;renderEventList(title,copy,predicate)});$('#eventPeriodFilter')?.addEventListener('change',e=>{state.eventPeriod=e.target.value;renderEventList(title,copy,predicate)});$('#eventFilterReset')?.addEventListener('click',()=>{state.eventTeam='';state.eventPeriod='upcoming';renderEventList(title,copy,predicate)});$$('[data-roster-toggle]').forEach(b=>b.addEventListener('click',()=>toggleEventRoster(b.dataset.rosterToggle,b)));bindEventDetailActions();
  }

  function renderTeams(){
    if(!state.selectedTeam&&state.teams[0])state.selectedTeam=state.teams[0].id;const selected=teamById(state.selectedTeam),roster=selected?teamPlayers(selected.id):[],att=selected?teamAttendance(selected.id):attendanceSummary([]);
    $('#viewContent').innerHTML=`<div class="page-intro"><div><h2>Csapatok</h2><p>Csapatkeret, alapadatok és tényleges jelenléti összesítés.</p></div><span class="read-only-badge">READ-ONLY</span></div>
      <div class="team-master-detail"><div class="team-master-list">${state.teams.map(t=>`<button type="button" class="team-master-card ${text(t.id)===text(state.selectedTeam)?'active':''}" data-team-id="${esc(t.id)}" style="--team-color:${esc(t.color||'#f7b700')}"><span class="team-color-bar"></span><div><b>${esc(t.name)}</b><small>${esc(t.season||cfg.DEFAULT_SEASON)} · ${esc(t.playerCount??teamPlayers(t.id).length)} fő</small></div><span>›</span></button>`).join('')||emptyInline('Nincs csapat.')}</div>
      <article class="panel team-detail-panel">${selected?`<div class="team-detail-head"><div><span class="eyebrow">${esc(selected.season||cfg.DEFAULT_SEASON)}</span><h3>${esc(selected.name)}</h3></div><span class="team-detail-dot" style="background:${esc(selected.color||'#f7b700')}"></span></div><div class="detail-grid">${detailPair('Edző(k)',selected.coaches)}${detailPair('Alaphelyszín',selected.defaultVenue)}${detailPair('Alappálya',selected.defaultCourt)}${detailPair('Aktív játékosok',roster.length)}${detailPair('Edzésjelenlét',pctText(att.trainingPresent,att.trainingMarked))}${detailPair('Meccsjelenlét',pctText(att.matchPresent,att.matchMarked))}</div><div class="panel-subhead"><div><h4>Játékoskeret</h4><p>Lezárt jelenléti adatok alapján.</p></div></div><div class="roster-list">${roster.map(p=>`<button class="roster-player" type="button" data-player-id="${esc(p.playerId)}">${avatarHtml(p,'small')}<div><b>${esc(p.displayName||p.name)}</b><small>${esc(p.position||'–')} · ${p.jerseyNo!=null?'#'+esc(p.jerseyNo):'nincs mezszám'}${p.membershipStartsOn?' · '+esc(fmtDate(p.membershipStartsOn))+' óta':''}</small></div><span class="roster-att">${esc(pctText(p.trainingPresent,p.trainingMarked))}</span><span>›</span></button>`).join('')||emptyInline('Nincs aktív játékos a csapatban.')}</div>`:emptyInline('Válassz csapatot.')}</article></div>`;
    $$('[data-team-id]').forEach(b=>b.addEventListener('click',()=>{state.selectedTeam=b.dataset.teamId;renderTeams()}));$$('[data-player-id]').forEach(b=>b.addEventListener('click',()=>openPlayerDetail(b.dataset.playerId)));
  }

  function medicalClass(v){const d=safeDate(v);if(!d)return'';const days=(d-Date.now())/864e5;return days<0?'medical-expired':days<92?'medical-warn':''}
  function playerRows(){const q=state.playerSearch.toLocaleLowerCase('hu');return state.players.filter(p=>{if(state.playerTeam&&text(p.teamId||p.team_id)!==state.playerTeam)return false;if(q&&!`${p.name||''} ${p.displayName||''} ${p.email||''} ${p.licenseNo||''}`.toLocaleLowerCase('hu').includes(q))return false;return true})}
  function playerTableRow(p){return `<tr class="clickable-row" tabindex="0" data-player-id="${esc(p.playerId)}"><td class="player-cell player-name-cell">${avatarHtml(p,'table')}<span><b>${esc(p.displayName||p.name||'–')}</b><small>${esc(p.email||'')}</small></span></td><td><b>${esc(p.teamName||'–')}</b>${p.membershipStartsOn?`<small>${esc(fmtDate(p.membershipStartsOn))} óta</small>`:''}</td><td>${esc(p.position||'–')}</td><td>${esc(p.jerseyNo??'–')}</td><td>${esc(p.licenseNo||'–')}</td><td class="${medicalClass(p.medicalValidUntil)}">${esc(p.medicalValidUntil?fmtDate(p.medicalValidUntil):'–')}</td><td><span class="status-pill ${p.hasAccount?'ok':''}">${p.hasAccount?'AKTÍV FIÓK':'NINCS FIÓK'}</span></td><td><b>${esc(p.trainingPresent??0)}/${esc(p.trainingMarked??0)}</b><small>${esc(pctText(p.trainingPresent,p.trainingMarked))}</small></td><td><b>${esc(p.matchPresent??0)}/${esc(p.matchMarked??0)}</b><small>${esc(pctText(p.matchPresent,p.matchMarked))}</small></td></tr>`}
  function playerCard(p){return `<button class="player-card parity-player-card" type="button" data-player-id="${esc(p.playerId)}">${avatarHtml(p,'card')}<div class="player-card-main"><div class="player-card-head"><b>${esc(p.displayName||p.name||'–')}</b><span>${p.jerseyNo!=null?'#'+esc(p.jerseyNo):''}</span></div><small>${esc(p.teamName||'Nincs aktív csapat')} · ${esc(p.position||'–')}</small><div class="player-card-stats"><span>Edzés <b>${esc(pctText(p.trainingPresent,p.trainingMarked))}</b></span><span>Meccs <b>${esc(pctText(p.matchPresent,p.matchMarked))}</b></span><span>${p.hasAccount?'Fiók aktív':'Nincs fiók'}</span></div></div><span class="chevron">›</span></button>`}
  function renderPlayers(){const rows=playerRows(),active=!!state.playerTeam||!!state.playerSearch;$('#viewContent').innerHTML=`<div class="page-intro"><div><h2>Játékosok</h2><p>Teljes sportolói adatbázis · teljes nevek · csapattagság · sportorvosi · tényleges jelenlét.</p></div><span class="read-only-badge">READ-ONLY PARITY</span></div><div class="filter-bar player-filter-bar"><label class="search-field"><span class="sr-only">Keresés</span><input id="playerSearch" type="search" value="${esc(state.playerSearch)}" placeholder="Keresés név, email vagy igazolási szám alapján…"></label><label class="field compact"><span>Csapat</span><select id="playerTeamFilter">${teamOptions(state.playerTeam)}</select></label><button class="filter-reset" id="playerFilterReset" ${active?'':'hidden'} type="button">Szűrők törlése</button></div><article class="panel player-surface"><div class="table-summary"><span><b>${rows.length}</b> játékos</span><span>Read-only</span></div><div class="responsive-table-wrap"><table class="data-table parity-player-table"><thead><tr><th>Név</th><th>Csapat / tagság</th><th>Poszt</th><th>#</th><th>Igazolás</th><th>Sportorvosi</th><th>Fiók</th><th>Edzés</th><th>Meccs</th></tr></thead><tbody>${rows.map(playerTableRow).join('')}</tbody></table></div><div class="player-card-list">${rows.map(playerCard).join('')}</div></article>`;const input=$('#playerSearch');let timer;input?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{state.playerSearch=input.value;renderPlayers()},180)});$('#playerTeamFilter')?.addEventListener('change',e=>{state.playerTeam=e.target.value;renderPlayers()});$('#playerFilterReset')?.addEventListener('click',()=>{state.playerTeam='';state.playerSearch='';renderPlayers()});$$('[data-player-id]').forEach(el=>{el.addEventListener('click',()=>openPlayerDetail(el.dataset.playerId));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPlayerDetail(el.dataset.playerId)}})})}
  function openPlayerDetail(id){const p=playerById(id);if(!p)return;state.selectedPlayer=id;const d=$('#entityDialog'),body=$('#entityDialogBody'),title=$('#entityDialogTitle');if($('#entityDialogEyebrow'))$('#entityDialogEyebrow').textContent='VERSENYSPORT · JÁTÉKOS';title.textContent=p.displayName||p.name||'Játékos';body.innerHTML=`<div class="entity-hero">${avatarHtml(p,'large')}<div><b>${esc(p.teamName||'Nincs aktív csapat')}</b><span>${esc(p.position||'–')}${p.jerseyNo!=null?' · #'+esc(p.jerseyNo):''}</span></div></div><div class="detail-grid">${detailPair('Email',p.email)}${detailPair('Igazolási szám',p.licenseNo)}${detailPair('Sportorvosi',p.medicalValidUntil?fmtDate(p.medicalValidUntil):'–',medicalClass(p.medicalValidUntil))}${detailPair('Tagság kezdete',p.membershipStartsOn?fmtDate(p.membershipStartsOn):'–')}${detailPair('Mezméret',p.jerseySize)}${detailPair('Nadrágméret',p.shortsSize)}${detailPair('Fiók',p.hasAccount?'Aktív':'Nincs összekapcsolva')}${detailPair('Státusz',p.active===false?'Inaktív':'Aktív')}</div><div class="attendance-detail"><div><small>Edzésjelenlét</small><b>${esc(p.trainingPresent??0)}/${esc(p.trainingMarked??0)}</b><span>${esc(pctText(p.trainingPresent,p.trainingMarked))}</span></div><div><small>Meccsjelenlét</small><b>${esc(p.matchPresent??0)}/${esc(p.matchMarked??0)}</b><span>${esc(pctText(p.matchPresent,p.matchMarked))}</span></div></div><div class="read-only-note">V0.4.2B parity: a korábbi Manager adatstruktúrája megmarad; a további szerkesztési funkciók a következő write-fázisokban kerülnek át.</div>`;d?.showModal()}

  function startOfWeek(d){const x=new Date(d);x.setHours(0,0,0,0);const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day);return x}
  function calendarWindow(){const a=new Date(state.calendarAnchor);a.setHours(0,0,0,0);if(state.calendarMode==='day'){const to=new Date(a);to.setDate(to.getDate()+1);return{from:a,to}}if(state.calendarMode==='month'){return{from:new Date(a.getFullYear(),a.getMonth(),1),to:new Date(a.getFullYear(),a.getMonth()+1,1)}}if(state.calendarMode==='season'){const y=a.getMonth()>=7?a.getFullYear():a.getFullYear()-1;return{from:new Date(y,7,1),to:new Date(y+1,7,1)}}const from=startOfWeek(a),to=new Date(from);to.setDate(to.getDate()+7);return{from,to}}
  function calendarRangeText(){const {from,to}=calendarWindow(),end=new Date(to.getTime()-1);return state.calendarMode==='day'?fmtDate(from):`${fmtDate(from)} – ${fmtDate(end)}`}
  function calendarFiltered(){return state.calendarEvents.filter(e=>(!state.calendarTeam||eventTeamId(e)===state.calendarTeam)&&(!state.calendarType||eventType(e)===state.calendarType)).sort((a,b)=>eventStart(a)-eventStart(b))}
  function agendaHtml(rows){const groups=new Map();rows.forEach(e=>{const d=eventStart(e);if(!d)return;const k=localDateKey(d);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(e)});return groups.size?Array.from(groups.entries()).map(([key,items])=>`<div class="calendar-day"><div class="calendar-date">${esc(fmtDay(key+'T12:00:00Z'))}</div><div class="calendar-events">${items.map(e=>`<div class="calendar-event ${isEventPast(e)?'past':''}"><time>${esc(fmtTime(eventStart(e)))}</time><span class="dot" style="background:${esc(e.color||'#f7b700')}"></span><div><strong>${esc(e.title||((eventType(e)==='match')?'Meccs':'Edzés'))}</strong><small>${esc(e.teamName||'')} · ${esc(eventPlace(e))}</small>${rsvpPills(e)}</div><span class="event-kind">${eventType(e)==='match'?'MECCS':'EDZÉS'}</span></div>`).join('')}</div></div>`).join(''):emptyInline('Ebben az időszakban nincs esemény.')}
  function weekGridHtml(rows){const from=startOfWeek(state.calendarAnchor),days=Array.from({length:7},(_,i)=>{const d=new Date(from);d.setDate(d.getDate()+i);return d});const slots=[];for(let h=17;h<=22;h++){for(const m of [0,30]){if(h===17&&m===0)continue;slots.push({h,m,label:`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`})}}const byDay=new Map(days.map((d,i)=>[localDateKey(d),i]));const cellMap=new Map();rows.forEach(e=>{const s=eventStart(e);if(!s)return;const key=localDateKey(s),di=byDay.get(key);if(di==null)return;const parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Budapest',hour:'2-digit',minute:'2-digit',hour12:false}).format(s).split(':');let mins=Number(parts[0])*60+Number(parts[1]);const slot=Math.max(0,Math.min(slots.length-1,Math.round((mins-(17*60+30))/30)));const ck=`${di}:${slot}`;if(!cellMap.has(ck))cellMap.set(ck,[]);cellMap.get(ck).push(e)});return `<div class="week-grid-wrap"><div class="week-grid"><div class="week-head corner"></div>${days.map(d=>`<div class="week-head"><b>${esc(new Intl.DateTimeFormat('hu-HU',{weekday:'short',timeZone:'Europe/Budapest'}).format(d))}</b><span>${esc(new Intl.DateTimeFormat('hu-HU',{month:'2-digit',day:'2-digit',timeZone:'Europe/Budapest'}).format(d))}</span></div>`).join('')}${slots.map((s,si)=>`<div class="week-time">${s.label}</div>${days.map((d,di)=>`<div class="week-cell">${(cellMap.get(`${di}:${si}`)||[]).map(e=>`<div class="week-event ${eventType(e)==='match'?'match':''}" style="--event-color:${esc(e.color||'#f7b700')}" title="${esc(e.title||'Esemény')}"><b>${esc(fmtTime(eventStart(e)))}</b><span>${esc(e.teamName||'')}</span><small>${esc(e.title||'Edzés')}</small></div>`).join('')}</div>`).join('')}`).join('')}</div></div>`}
  function renderCalendar(){
    if(state.area!=='competition'){renderPlaceholder('Naptár','A Tömegsport naptár production parityje külön scoped RPC-vel kerül át.',['heti alapnézet','pálya/terem erőforrások','kapacitás és jelentkezések']);return}
    const filtered=calendarFiltered(),active=!!state.calendarTeam||!!state.calendarType;
    $('#viewContent').innerHTML=`<div class="page-intro"><div><h2>Naptár</h2><p>Heti időrács desktopon, kompakt agenda mobilon; ugyanabból a Supabase eseményforrásból.</p></div><div class="toolbar-actions"><div class="segmented calendar-modes" role="group" aria-label="Naptár nézet"><button class="${state.calendarMode==='day'?'active':''}" data-calendar-mode="day">NAP</button><button class="${state.calendarMode==='week'?'active':''}" data-calendar-mode="week">HÉT</button><button class="${state.calendarMode==='month'?'active':''}" data-calendar-mode="month">HÓNAP</button><button class="${state.calendarMode==='season'?'active':''}" data-calendar-mode="season">SZEZON</button></div><button class="icon-button filter-toggle" id="calendarFilterBtn" type="button" aria-label="Szűrők" aria-expanded="false"><span>▽</span></button></div></div><div class="filter-panel" id="calendarFilterPanel" hidden><label class="field compact"><span>Csapat</span><select id="calendarTeamFilter">${teamOptions(state.calendarTeam)}</select></label><label class="field compact"><span>Típus</span><select id="calendarTypeFilter"><option value="" ${state.calendarType===''?'selected':''}>Minden esemény</option><option value="training" ${state.calendarType==='training'?'selected':''}>Edzés</option><option value="match" ${state.calendarType==='match'?'selected':''}>Meccs</option></select></label><button class="filter-reset" id="calendarFilterReset" type="button" ${active?'':'hidden'}>Szűrők törlése</button></div><article class="panel calendar-panel"><div class="calendar-nav"><button class="button quiet" id="calendarPrev" type="button">← Előző</button><button class="button quiet" id="calendarToday" type="button">Ma</button><strong>${esc(calendarRangeText())}</strong><button class="button quiet" id="calendarNext" type="button">Következő →</button></div><div class="desktop-week-grid">${state.calendarMode==='week'?weekGridHtml(filtered):agendaHtml(filtered)}</div><div class="mobile-calendar-agenda">${agendaHtml(filtered)}</div></article>`;bindCalendarUi()
  }
  function bindCalendarUi(){$('#calendarFilterBtn')?.addEventListener('click',()=>{const b=$('#calendarFilterBtn'),open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));$('#calendarFilterPanel').hidden=!open});$('#calendarTeamFilter')?.addEventListener('change',e=>{state.calendarTeam=e.target.value;configured()?loadCalendar().then(renderCalendar).catch(err=>status(err.message,'error')):renderCalendar()});$('#calendarTypeFilter')?.addEventListener('change',e=>{state.calendarType=e.target.value;renderCalendar()});$('#calendarFilterReset')?.addEventListener('click',()=>{state.calendarTeam='';state.calendarType='';configured()?loadCalendar().then(renderCalendar).catch(err=>status(err.message,'error')):renderCalendar()});$$('[data-calendar-mode]').forEach(b=>b.addEventListener('click',()=>{state.calendarMode=b.dataset.calendarMode;configured()?loadCalendar().then(renderCalendar).catch(err=>status(err.message,'error')):renderCalendar()}));$('#calendarPrev')?.addEventListener('click',()=>shiftCalendar(-1));$('#calendarNext')?.addEventListener('click',()=>shiftCalendar(1));$('#calendarToday')?.addEventListener('click',()=>{state.calendarAnchor=new Date();configured()?loadCalendar().then(renderCalendar).catch(err=>status(err.message,'error')):renderCalendar()})}
  function shiftCalendar(dir){const d=new Date(state.calendarAnchor);if(state.calendarMode==='day')d.setDate(d.getDate()+dir);else if(state.calendarMode==='month')d.setMonth(d.getMonth()+dir);else if(state.calendarMode==='season')d.setFullYear(d.getFullYear()+dir);else d.setDate(d.getDate()+7*dir);state.calendarAnchor=d;configured()?loadCalendar().then(renderCalendar).catch(err=>status(err.message,'error')):renderCalendar()}

  function adminPermissionSummary(a){const p=Array.isArray(a?.permissions)?a.permissions:[],mods=new Set(p.filter(x=>x.canView||x.canEdit||x.canNotify).map(x=>text(x.moduleKey)));return `${mods.size} modul · ${p.filter(x=>x.canEdit).length} szerkesztési scope`}
  function adminListHtml(){if(state.adminsLoadError)return `<div class="migration-note error"><b>Az MGR004 admin-kezelő még nincs telepítve.</b><span>${esc(state.adminsLoadError)}</span></div>`;return `<div class="admin-list">${(state.admins||[]).map(a=>`<button class="admin-list-row ${text(state.adminEditId)===text(a.id)?'active':''}" type="button" data-admin-edit="${esc(a.id)}"><span class="profile-dot">${esc(initials(a.displayName||a.email))}</span><div><b>${esc(a.displayName||a.email)}</b><small>${esc(a.email)} · ${esc(adminPermissionSummary(a))}</small></div><span class="status-pill ${a.active?'ok':'muted'}">${a.active?'AKTÍV':'INAKTÍV'}</span></button>`).join('')||emptyInline('Nincs Manager-fiók.')}</div>`}
  function permissionRowsForAdmin(admin,key){return (admin?.permissions||[]).filter(p=>text(p.moduleKey)===key)}
  function adminPermissionEditorRow(admin,key,label){const rows=permissionRowsForAdmin(admin,key),canView=rows.some(x=>x.canView),canEdit=rows.some(x=>x.canEdit),canNotify=rows.some(x=>x.canNotify),competition=key.startsWith('competition.'),global=competition&&rows.some(x=>!x.teamId),selected=new Set(rows.filter(x=>x.teamId).map(x=>text(x.teamId))),teams=(state.adminTeams.length?state.adminTeams:state.teams).filter(t=>t.active!==false);return `<div class="admin-permission-row" data-admin-module-row="${esc(key)}"><div class="admin-module-name"><b>${esc(label)}</b><small>${esc(key)}</small></div><label><input type="checkbox" data-right="view" ${canView?'checked':''}> Nézet</label><label><input type="checkbox" data-right="edit" ${canEdit?'checked':''}> Szerk.</label><label><input type="checkbox" data-right="notify" ${canNotify?'checked':''}> Értesítés</label>${competition?`<div class="admin-team-scope"><label class="scope-all"><input type="checkbox" data-scope-all ${global?'checked':''}> Minden csapat</label>${teams.map(t=>`<label><input type="checkbox" data-scope-team value="${esc(t.id)}" ${!global&&selected.has(text(t.id))?'checked':''} ${global?'disabled':''}><span class="team-color-mini" style="background:${esc(t.color||'#f7b700')}"></span>${esc(t.name)}</label>`).join('')}</div>`:'<div class="admin-team-scope muted-scope">Klubszintű</div>'}</div>`}
  function adminEditorHtml(){const isNew=state.adminEditId==='__new__',admin=isNew?{id:'',email:'',displayName:'',active:true,permissions:[]}:(state.admins||[]).find(a=>text(a.id)===text(state.adminEditId));if(!admin)return `<div class="admin-editor-empty"><b>Válassz egy admint</b><span>Vagy hozz létre új Manager-fiókot.</span></div>`;return `<div class="admin-editor" data-admin-id="${esc(admin.id||'')}"><div class="admin-editor-head"><div><h3>${isNew?'Új admin':'Admin szerkesztése'}</h3><p>${admin.authBound?'A fiók már Supabase Auth felhasználóhoz van kötve.':'Az első sikeres OTP belépéskor kapcsolódik az Auth-fiókhoz.'}</p></div>${!isNew?`<span class="status-pill ${admin.authBound?'ok':''}">${admin.authBound?'AUTH KÖTVE':'MÉG NEM LÉPETT BE'}</span>`:''}</div><div class="admin-account-grid"><label class="field"><span>Név</span><input id="adminDisplayName" value="${esc(admin.displayName||'')}" placeholder="Név"></label><label class="field"><span>Email</span><input id="adminEmail" type="email" value="${esc(admin.email||'')}" ${admin.authBound?'readonly':''} placeholder="nev@example.com"></label><label class="admin-active-toggle"><input id="adminActive" type="checkbox" ${admin.active!==false?'checked':''} ${admin.isSelf?'disabled':''}><span>Aktív Manager-fiók</span></label></div><div class="admin-permission-toolbar"><div><b>Jogosultságok</b><small>View / Edit / Notify, Versenysportnál csapat-scope-pal.</small></div><div><button class="button quiet small" id="adminViewAllBtn" type="button">Minden megtekintés</button><button class="button quiet small" id="adminFullBtn" type="button">Teljes admin</button></div></div><div class="admin-permission-groups">${ADMIN_MODULES.map(g=>`<section><h4>${esc(g.group)}</h4>${g.items.map(([k,l])=>adminPermissionEditorRow(admin,k,l)).join('')}</section>`).join('')}</div><div class="admin-editor-actions"><button class="button primary" id="adminSaveBtn" type="button" ${state.adminBusy?'disabled':''}>${state.adminBusy?'Mentés…':'Mentés'}</button><button class="button quiet" id="adminCancelBtn" type="button">Mégse</button></div></div>`}
  function collectAdminPermissionPayload(){const out=[];$$('[data-admin-module-row]').forEach(row=>{const key=row.dataset.adminModuleRow,view=row.querySelector('[data-right="view"]')?.checked===true,edit=row.querySelector('[data-right="edit"]')?.checked===true,notify=row.querySelector('[data-right="notify"]')?.checked===true;if(!(view||edit||notify))return;if(key.startsWith('competition.')){const all=row.querySelector('[data-scope-all]')?.checked===true,teams=Array.from(row.querySelectorAll('[data-scope-team]')).filter(x=>x.checked).map(x=>x.value);if(all||!teams.length)out.push({moduleKey:key,teamId:null,canView:view,canEdit:edit,canNotify:notify});else teams.forEach(teamId=>out.push({moduleKey:key,teamId,canView:view,canEdit:edit,canNotify:notify}))}else out.push({moduleKey:key,teamId:null,canView:view,canEdit:edit,canNotify:notify})});return out}
  async function saveAdminEditorSafe(){if(state.adminBusy)return;const email=text($('#adminEmail')?.value).toLowerCase(),name=text($('#adminDisplayName')?.value),active=$('#adminActive')?.checked!==false,payload=collectAdminPermissionPayload();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){status('Adj meg érvényes admin email címet.','error');return}const existing=state.adminEditId==='__new__'?null:(state.admins||[]).find(a=>text(a.id)===text(state.adminEditId));state.adminBusy=true;renderSettings();try{status('Admin és jogosultságok mentése…');const saved=await rpc('cc_manager_admin_save_v1',{p_manager_id:existing?.id||null,p_email:email,p_display_name:name,p_active:active,p_permissions:payload});await loadAdmins();state.adminEditId=text(saved?.account?.id||existing?.id);status('Admin mentve.','success')}catch(err){console.error(err);status(err.message||'Az admin mentése sikertelen.','error')}finally{state.adminBusy=false;renderSettings()}}
  function bindAdminEditor(){$$('[data-admin-edit]').forEach(b=>b.addEventListener('click',()=>{state.adminEditId=b.dataset.adminEdit;renderSettings()}));$('#adminAddBtn')?.addEventListener('click',()=>{state.adminEditId='__new__';renderSettings()});$('#adminCancelBtn')?.addEventListener('click',()=>{state.adminEditId='';renderSettings()});$('#adminSaveBtn')?.addEventListener('click',saveAdminEditorSafe);$('#adminViewAllBtn')?.addEventListener('click',()=>{$$('[data-admin-module-row]').forEach(r=>{const v=r.querySelector('[data-right="view"]');if(v)v.checked=true});});$('#adminFullBtn')?.addEventListener('click',()=>{$$('[data-admin-module-row]').forEach(r=>{['view','edit','notify'].forEach(k=>{const x=r.querySelector(`[data-right="${k}"]`);if(x)x.checked=true});const all=r.querySelector('[data-scope-all]');if(all){all.checked=true;Array.from(r.querySelectorAll('[data-scope-team]')).forEach(x=>{x.checked=false;x.disabled=true})}})});$$('[data-scope-all]').forEach(x=>x.addEventListener('change',()=>{Array.from(x.closest('[data-admin-module-row]').querySelectorAll('[data-scope-team]')).forEach(t=>{t.disabled=x.checked;if(x.checked)t.checked=false})}))}
  function renderSettings(){const canManage=canAction('settings','edit');$('#viewContent').innerHTML=`<div class="page-intro"><div><h2>Beállítások</h2><p>Megjelenés, Manager-fiókok és jogosultságok.</p></div><span class="read-only-badge ${canManage?'write-enabled':''}">${canManage?'ADMIN WRITE':'VIEW'}</span></div><div class="settings-layout"><article class="panel"><div class="setting-row"><div><strong>Megjelenés</strong><small>Világos / sötét téma ezen az eszközön.</small></div><button class="button quiet" id="themeToggle" type="button">Téma váltása</button></div><div class="setting-row"><div><strong>Manager PWA</strong><small>${esc(cfg.BUILD)}</small></div><span class="status-pill ok">V0.4.2B</span></div><div class="setting-row"><div><strong>Edzéstervezés</strong><small>A régi Manager parity következő köre.</small></div><span class="status-pill">KÖVETKEZŐ</span></div></article>${canManage?`<article class="panel admin-panel"><div class="panel-head"><div><h3>Adminok és jogosultságok</h3><p>Manager hozzáférés e-mail alapján, modul- és csapatscope-pal.</p></div><button class="button primary small" id="adminAddBtn" type="button" ${state.adminsLoadError?'disabled':''}>+ Új admin</button></div><div class="admin-layout"><div>${adminListHtml()}</div><div>${adminEditorHtml()}</div></div></article>`:''}</div>`;$('#themeToggle')?.addEventListener('click',()=>{const dark=document.body.classList.toggle('dark');localStorage.setItem('cc-manager-theme',dark?'dark':'light')});if(canManage)bindAdminEditor()}

  function renderView(){renderModule();document.title=`${state.module==='settings'?'Beállítások':moduleMeta()?.[1]||'Manager'} – Club Control Manager`}

  async function refresh(){if(!configured()){status('Manager PWA konfigurációs hiba.','error');return}try{await loadLiveData()}catch(_){}}
  function bindStaticUi(){
    $$('.area-button,.area-choice').forEach(b=>b.addEventListener('click',()=>{switchArea(b.dataset.area);$('#areaDialog')?.close()}));
    $('#mobileAreaBtn')?.addEventListener('click',()=>$('#areaDialog')?.showModal());$('#areaDialogClose')?.addEventListener('click',()=>$('#areaDialog')?.close());$('#mobileMoreClose')?.addEventListener('click',()=>$('#mobileMoreDialog')?.close());
    ['areaDialog','mobileMoreDialog'].forEach(id=>$('#'+id)?.addEventListener('click',e=>{if(e.target===$('#'+id))$('#'+id).close()}));
    $('#refreshBtn')?.addEventListener('click',refresh);$('#managerMenuBtn')?.addEventListener('click',()=>$('#accountDialog')?.showModal());$('#accountDialogClose')?.addEventListener('click',()=>$('#accountDialog')?.close());$('#accountDialog')?.addEventListener('click',e=>{if(e.target===$('#accountDialog'))$('#accountDialog').close()});
    $('#logoutBtn')?.addEventListener('click',async()=>{if(state.supabase)await state.supabase.auth.signOut({scope:'local'});location.reload()});
    $('#entityDialogClose')?.addEventListener('click',()=>$('#entityDialog')?.close());$('#entityDialog')?.addEventListener('click',e=>{if(e.target===$('#entityDialog'))$('#entityDialog').close()});
    $('#requestCodeBtn')?.addEventListener('click',requestCode);$('#verifyCodeBtn')?.addEventListener('click',verifyCode);$('#changeEmailBtn')?.addEventListener('click',()=>showLogin('loginEmailStep'));$('#loginEmail')?.addEventListener('keydown',e=>{if(e.key==='Enter')requestCode()});$('#loginCode')?.addEventListener('keydown',e=>{if(e.key==='Enter')verifyCode()});$('#loginCode')?.addEventListener('input',e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,10)});
    window.addEventListener('popstate',()=>{resolveInitialRoute();renderChrome();renderView()});
  }

  async function boot(){
    if(localStorage.getItem('cc-manager-theme')==='dark')document.body.classList.add('dark');resolveInitialRoute();bindStaticUi();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(err=>console.warn('SW:',err));
    if(!configured()){hideLogin();status('Manager PWA konfigurációs hiba: a Supabase kapcsolat nincs beállítva.','error');renderChrome();renderView();return}
    try{state.supabase=await createSupabase();showLogin('loginLoadingStep');const {data:{session},error}=await state.supabase.auth.getSession();if(error)throw error;state.session=session||null;if(!session){showLogin('loginEmailStep');return}await loadLiveData();hideLogin();if(!location.hash)setRoute(state.area,'overview',{replace:true})}catch(err){console.error(err);status(err.message||'Manager indítási hiba.','error');showLogin('loginEmailStep')}
  }

  boot();
})();
